### PR TITLE
Joshua Clements - Midterm

### PR DESCRIPTION
**Pull request by joshuayclements**
@alohavolha @lusead

### CODE REVIEW

**Comment by joshuayclements** [comment]
http://joshuayclements.github.io/midterm/

**Comment by joshuayclements** [comment]
@micjamking Final Submission

**Comment by alohavolha** [comment]
looks G

**Comment by lusead** [comment]
Looks good! Nice and tidy

**Comment by micjamking** [comment]
Hi Josh,

Your typography looks good, however justified text in responsive designs can be a bit awkward, since it can break and stretch words in weird ways to fit the width. Other than that, great job!
- Mike

**Pull request closed without merging**
